name: get_modular_wrappers
description: GetX modular approach wrapper
version: 0.0.3
homepage: https://github.com/luisburgos/get_modular

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  event_bus: ^2.0.0
  get: ^4.6.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  coverage: ^1.0.2
  mockito: 5.3.0
